### ISSUE TITLE
Circular reference

### ISSUE THREAD

**Issue by emgiezet** [maschmann/TranslationLoaderBundle#16]
Helo!

Just found Your bundle but when trying to install it on sf2.3 it geve me:

```
 Circular reference detected for service "doctrine.orm.default_entity_manager", path: "doctrine.orm.default_entity_manager -> doctrine.dbal.default_connection -> asm_translation_loader.history.subscriber -> security.context -> security.authentication.manager -> fos_user.user_provider.username_email -> fos_user.user_manager". 
```

and

```
 Circular reference detected for service "doctrine.orm.default_entity_manager", path: "routing.loader -> assetic.asset_manager -> twig -> twig.extension.render_module -> doctrine.orm.default_entity_manager -> doctrine.dbal.default_connection -> asm_translation_loader.history.subscriber -> security.context -> security.authentication.manager -> fos_user.user_provider.username_email -> fos_user.user_manager".
```

My config.yml looks like this:

```
asm_translation_loader:
    resources:
        pl: ~
        en: ~
    driver: orm
    history: false # default false
    database:
        entity_manager: doctrine.orm.default_entity_manager
```

Right now have no more time to debug it. Bu on the weekend i will be able to look at this little more.

My first shoot is that the FOSUserBundle making some trouble here.

Kind regards!
Max
